name: "Semantic Version"
description: "Determines version of a repo"
branding:
  icon: "layers"
  color: "blue"
inputs:
  branch:
    description: "The branch name"
    required: true
    default: "master"
  tag_prefix:
    description: "The prefix to use to identify tags"
    required: true
    default: "v"
  major_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a major (breaking) change"
    required: true
    default: "(MAJOR)"
  minor_pattern:
    description: "a string which, if present in a git commit, indicates that a change represents a minor (feature) change"
    required: true
    default: "(MINOR)"

outputs:
  major:
    description: "Current major number"
  minor:
    description: "Current minor number"
  patch:
    description: "Current patch number"
  increment:
    description: "An additional value indicating the number of commits for the current version"
  version:
    description: "The version result, in the format {major}.{minor}.{patch}"
runs:
  using: "node12"
  main: "dist/index.js"
