name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NPM Install
        run: npm ci
      - name: Test
        run: git config --global user.name "Test User" && git config --global user.email "test@example.com" && npm test
      - name: Package
        run: npm run package
      - name: Run Action
        uses: ./
        id: run
        with:
          main-branch: master
          release-branch: release
